### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by cueedee** [bmac/grunt-coffee-jshint#10]
@bmac, I would like to `npm publish` a new release, only to find I lack the permissions to do so. Would you like to do the honours please?

**Comment by bmac** [comment]
@cueedee what is your username on npm?

**Comment by cueedee** [comment]
@bmac, it's org.npmjs.718039.david@distelpluis.nl

**Comment by bmac** [comment]
Just published it and added you as an owner on npm.

**Comment by cueedee** [comment]
Thanks!
