### ISSUE TITLE
Consider upgrading grunt-coffee-jshint's dependencies

### ISSUE THREAD

**Issue by cueedee** [bmac/grunt-coffee-jshint#6]
Hi,

Please consider upgrading all `grunt-coffee-jshint`'s dependencies. Most notably, [`coffee-jshint`'s latest](https://github.com/Clever/coffee-jshint/releases) (now at `0.2.2`) doesn't match the `~0.0.14` range that `grunt-coffee-jshint` currently requires.

**Comment by bmac** [comment]
Hi @cueedee. Would you like to submit a pr updating the package.json? I'd be happy to merge it.

**Comment by cueedee** [comment]
Sure thing. `coffee-jshint` happens to be in the middle of upgrading its dependencies as well. Shall I wait for that to complete, or just submit the PR now and another one later?
